const PERMISSIONS = {
  VIEW: 'view',
  CREATE: 'create',
  EDIT_LIMITED: 'edit_limited',
  REQUEST_CORRECTION: 'request_correction',
  APPROVE_CORRECTION: 'approve_correction',
  FORWARD: 'forward',
  RETURN: 'return',
  APPROVE: 'approve',
  REJECT: 'reject',
  CLOSE: 'close',
  REOPEN: 'reopen',
  ADD_NOTE: 'add_note',
  EDIT_OWN_REMARK: 'edit_own_remark',
  VIEW_AUDIT: 'view_audit',
  EXPORT: 'export',
  PRINT: 'print',
  DOWNLOAD_PDF: 'download_pdf',
  MANAGE_USERS: 'manage_users',
  MANAGE_ROLES: 'manage_roles',
  MANAGE_DEPARTMENTS: 'manage_departments',
  MANAGE_COURSES: 'manage_courses',
};

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

const DEFAULT_ROLE_PERMISSIONS = {
  super_admin: ALL_PERMISSIONS,
  admin: ALL_PERMISSIONS,
  receptionist: [
    PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.REQUEST_CORRECTION,
    PERMISSIONS.FORWARD, PERMISSIONS.ADD_NOTE, PERMISSIONS.EDIT_OWN_REMARK,
    PERMISSIONS.PRINT, PERMISSIONS.DOWNLOAD_PDF,
  ],
  senior_receptionist: [
    PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT_LIMITED,
    PERMISSIONS.REQUEST_CORRECTION, PERMISSIONS.FORWARD, PERMISSIONS.RETURN,
    PERMISSIONS.ADD_NOTE, PERMISSIONS.EDIT_OWN_REMARK, PERMISSIONS.PRINT,
    PERMISSIONS.DOWNLOAD_PDF, PERMISSIONS.EXPORT,
  ],
  counsellor: [
    PERMISSIONS.VIEW, PERMISSIONS.EDIT_LIMITED, PERMISSIONS.REQUEST_CORRECTION,
    PERMISSIONS.FORWARD, PERMISSIONS.RETURN, PERMISSIONS.CLOSE,
    PERMISSIONS.ADD_NOTE, PERMISSIONS.EDIT_OWN_REMARK, PERMISSIONS.PRINT,
    PERMISSIONS.DOWNLOAD_PDF,
  ],
  counselling_head: [
    PERMISSIONS.VIEW, PERMISSIONS.EDIT_LIMITED, PERMISSIONS.REQUEST_CORRECTION,
    PERMISSIONS.APPROVE_CORRECTION, PERMISSIONS.FORWARD, PERMISSIONS.RETURN,
    PERMISSIONS.CLOSE, PERMISSIONS.ADD_NOTE, PERMISSIONS.EDIT_OWN_REMARK,
    PERMISSIONS.PRINT, PERMISSIONS.DOWNLOAD_PDF, PERMISSIONS.EXPORT,
  ],
  department_staff: [
    PERMISSIONS.VIEW, PERMISSIONS.EDIT_LIMITED, PERMISSIONS.REQUEST_CORRECTION,
    PERMISSIONS.FORWARD, PERMISSIONS.RETURN, PERMISSIONS.ADD_NOTE,
    PERMISSIONS.EDIT_OWN_REMARK, PERMISSIONS.PRINT, PERMISSIONS.DOWNLOAD_PDF,
  ],
  hod: [
    PERMISSIONS.VIEW, PERMISSIONS.EDIT_LIMITED, PERMISSIONS.REQUEST_CORRECTION,
    PERMISSIONS.APPROVE, PERMISSIONS.FORWARD, PERMISSIONS.RETURN,
    PERMISSIONS.ADD_NOTE, PERMISSIONS.EDIT_OWN_REMARK, PERMISSIONS.PRINT,
    PERMISSIONS.DOWNLOAD_PDF, PERMISSIONS.EXPORT,
  ],
  accounts_staff: [
    PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT_LIMITED,
    PERMISSIONS.REQUEST_CORRECTION, PERMISSIONS.FORWARD, PERMISSIONS.ADD_NOTE,
    PERMISSIONS.EDIT_OWN_REMARK, PERMISSIONS.PRINT, PERMISSIONS.DOWNLOAD_PDF,
  ],
  accounts_head: [
    PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT_LIMITED,
    PERMISSIONS.REQUEST_CORRECTION, PERMISSIONS.APPROVE_CORRECTION,
    PERMISSIONS.APPROVE, PERMISSIONS.FORWARD, PERMISSIONS.ADD_NOTE,
    PERMISSIONS.EDIT_OWN_REMARK, PERMISSIONS.PRINT, PERMISSIONS.DOWNLOAD_PDF,
    PERMISSIONS.EXPORT,
  ],
  registrar_staff: [
    PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT_LIMITED,
    PERMISSIONS.REQUEST_CORRECTION, PERMISSIONS.FORWARD, PERMISSIONS.APPROVE,
    PERMISSIONS.REJECT, PERMISSIONS.ADD_NOTE, PERMISSIONS.EDIT_OWN_REMARK,
    PERMISSIONS.PRINT, PERMISSIONS.DOWNLOAD_PDF,
  ],
  registrar: [
    PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT_LIMITED,
    PERMISSIONS.REQUEST_CORRECTION, PERMISSIONS.APPROVE_CORRECTION,
    PERMISSIONS.FORWARD, PERMISSIONS.APPROVE, PERMISSIONS.REJECT,
    PERMISSIONS.CLOSE, PERMISSIONS.ADD_NOTE, PERMISSIONS.EDIT_OWN_REMARK,
    PERMISSIONS.PRINT, PERMISSIONS.DOWNLOAD_PDF, PERMISSIONS.EXPORT,
  ],
  admission_head: [
    PERMISSIONS.VIEW, PERMISSIONS.EDIT_LIMITED, PERMISSIONS.APPROVE_CORRECTION,
    PERMISSIONS.FORWARD, PERMISSIONS.RETURN, PERMISSIONS.APPROVE,
    PERMISSIONS.REJECT, PERMISSIONS.CLOSE, PERMISSIONS.REOPEN,
    PERMISSIONS.ADD_NOTE, PERMISSIONS.EDIT_OWN_REMARK, PERMISSIONS.VIEW_AUDIT,
    PERMISSIONS.PRINT, PERMISSIONS.DOWNLOAD_PDF, PERMISSIONS.EXPORT,
  ],
  principal: [
    PERMISSIONS.VIEW, PERMISSIONS.VIEW_AUDIT, PERMISSIONS.EXPORT,
    PERMISSIONS.PRINT, PERMISSIONS.DOWNLOAD_PDF,
  ],
  auditor: [
    PERMISSIONS.VIEW, PERMISSIONS.VIEW_AUDIT, PERMISSIONS.EXPORT,
    PERMISSIONS.PRINT, PERMISSIONS.DOWNLOAD_PDF,
  ],
  event_coordinator: [
    PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT_LIMITED,
    PERMISSIONS.REQUEST_CORRECTION, PERMISSIONS.FORWARD, PERMISSIONS.CLOSE,
    PERMISSIONS.ADD_NOTE, PERMISSIONS.EDIT_OWN_REMARK, PERMISSIONS.PRINT,
    PERMISSIONS.DOWNLOAD_PDF,
  ],
  placement_staff: [
    PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT_LIMITED,
    PERMISSIONS.REQUEST_CORRECTION, PERMISSIONS.FORWARD, PERMISSIONS.CLOSE,
    PERMISSIONS.ADD_NOTE, PERMISSIONS.EDIT_OWN_REMARK, PERMISSIONS.PRINT,
    PERMISSIONS.DOWNLOAD_PDF,
  ],
};

module.exports = { PERMISSIONS, ALL_PERMISSIONS, DEFAULT_ROLE_PERMISSIONS };
